import type { Metadata } from "next";
import { ThemeProvider } from "@/tools/themeprovider";
import {ColorThemeProvider} from "@/tools/color-theme-provider";
import { Geist, Geist_Mono, Noto_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LoadingScreen from "@/tools/loadingscreen";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="h-full font-sans"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <ColorThemeProvider>
          <LoadingScreen>
            {children}
          </LoadingScreen>
          </ColorThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
